---
#插件列表
#pluginList:
#- "com.testerhome.appcrawler.plugin.FlowDiff"
#- "com.testerhome.appcrawler.plugin.ProxyPlugin"
#- "com.testerhome.appcrawler.plugin.TagLimitPlugin"
#- "com.testerhome.appcrawler.plugin.ReportPlugin"
reportTitle: AppCrawler-acp4.7
currentDriver: "android"
# 结果目录
resultDir: ""
# 最大运行时间
maxTime: 108000
logLevel: "TRACE"
#结果报告是否展示没有遍历被取消的控件
showCancel: true
#特定元素的tag布局层级完全一样时的遍历最大值
tagLimitMax: 8
#是否截图
saveScreen: true
screenshotTimeout: 20

# appium的capability通用配置
capability:
  newCommandTimeout: 120
  launchTimeout: 120000
  platformVersion: ""
  platformName: ""
# Appium是否需要自动安装和启动应用。默认值true  
  autoLaunch: "true"
# 直接转换到 WebView 上下文。 默认值 false    
  autoWebview: "false"
# 不要在会话前重置应用状态。默认值false。  
  noReset: "false"

# android专属配置 最后会和capability合并
androidCapability:
  appPackage: "com.yylending.las"
  appActivity: "com.yylending.las.splash.SplashActivity"
  # app: "D:/tool/cma-beta-3.2.0.184.apk"
  # 你想使用的自动化测试引擎 可以是 uiautomator2  macaca 等 默认appium
  automationName: appium
  appium: "http://127.0.0.1:4723/wd/hub"
  # macaca: "http://127.0.0.1:3456/wd/hub"
  fullReset: false
  noReset: true
  reuse: 3
  #以下为重置手机输入法为appium输入法
  unicodeKeyboard: true
  resetKeyboard: true


# iosCapability:
#   deviceName: "iPhone 6 Plus"
#   bundleId: "com.yyfax.ph"
#   screenshotWaitTimeout: "10"
#   platformVersion: "9.3"
#   autoAcceptAlerts: "true"
#   app: "/home/cmd/appcrawler/acp4.7p.apk"
#   appium: "http://127.0.0.1:4730/wd/hub"

#appWhiteList:
#- android
#- com.shafa.market

# 用来确定url的元素定位xpath 他的text会被取出当作url因素
#defineUrl:


# 设置一个起始url和maxDepth, 用来在遍历时候指定初始状态和遍历深度
#baseUrl:

# 默认的最大深度10, 结合baseUrl可很好的控制遍历的范围
maxDepth: 10

# 是否是前向遍历或者后向遍历
headFirst: true

# 是否遍历WebView控件
enterWebView: true

# url黑名单.用于排除某些页面
#urlBlackList:

#urlWhiteList:
#- ".*Main.*"

# 后退按钮标记, 主要用于iOS, xpath
#backButton:

# 优先遍历元素特征列表
# firstList:
#- "//*[contains(@resource-id,'com.acp.main:id/tvBottomTab4')]//android.widget.TextView"
# - "//*[contains(@resource-id,'com.acp.main:id/tvBottomTab3')]//android.widget.TextView"


# 默认遍历元素特征列表 需要注意的是firstList和lastList指定的元素必须包含在selectedList中
#selectedList:

# 最后遍历元素特征列表
#lastList:

# 黑名单列表 matches风格, 默认排除内容是2个数字以上的控件
# blackList:

# - "//*[contains(@resource-id,'com.acp.main:id/tvBottomTab4')]//android.widget.TextView"
# - //*[@resource-id='com.acp.main:id/module_tj1_name']    
# - //*[@resource-id='com.acp.main:id/module_tj1_description']

# 引导规则. name, value, times三个元素组成
# triggerActions:
#  - action: "15188100003"
#    xpath: "//android.widget.LinearLayout[@resource-id='com.yyfax.ph:id/login_layout']/android.widget.EditText[1]"
#    times: 1
#  - action: "a123456"
#    xpath: "//android.widget.LinearLayout[@resource-id='com.yyfax.ph:id/password_layout']/android.widget.EditText[1]"
#    times: 1
#  - action: "click"
#    xpath: "//*[@text='登录' and @class='android.widget.Button']"
#    times: 1

